/* eslint-disable */
// Sample data for the easysite admin prototype
// Primary site: 도화원플라워 (flower shop)

const SITES = [
  {
    id: "dohwawon",
    name: "도화원플라워",
    type: "flower",
    domain: "dohwawon.kr",
    color: "#d36a8a",
    gradient: "linear-gradient(135deg, #f4c8d0 0%, #d36a8a 100%)",
    logo: "도",
    operator: "박소연",
    operatorRole: "오너",
    lastPublishedAt: "2026-05-19 09:42",
  },
  {
    id: "bell_cake",
    name: "벨케이크",
    type: "cake",
    domain: "bellcake.kr",
    color: "#c9a567",
    gradient: "linear-gradient(135deg, #f0e3c2 0%, #c9a567 100%)",
    logo: "벨",
    operator: "이지은",
    operatorRole: "오너",
  },
  {
    id: "PARKHAD",
    name: "PARKHAD",
    type: "hair",
    domain: "parkhad.com",
    color: "#1a1d24",
    gradient: "linear-gradient(135deg, #c9cad0 0%, #1a1d24 100%)",
    logo: "PH",
    operator: "박정훈",
    operatorRole: "오너",
  },
  {
    id: "flower_example",
    name: "flower_example",
    type: "flower",
    domain: "flower-example.kr",
    color: "#7ba88a",
    gradient: "linear-gradient(135deg, #d8e6cf 0%, #7ba88a 100%)",
    logo: "fe",
    operator: "관리자",
    operatorRole: "오너",
  },
  {
    id: "greenlight_art",
    name: "풀빛그림아이 미술학원",
    type: "academy",
    domain: "greenlightart.kr",
    color: "#5e8edb",
    gradient: "linear-gradient(135deg, #ffd4a8 0%, #5e8edb 60%, #b58be8 100%)",
    logo: "풀",
    operator: "김선생",
    operatorRole: "오너",
  },
];

// Placeholder thumbnail svgs (gradient blobs) — encoded as data URIs
const flowerThumb = (h1, h2) =>
  `url("data:image/svg+xml;utf8,${encodeURIComponent(
    `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='${h1}'/><stop offset='1' stop-color='${h2}'/></linearGradient></defs><rect width='200' height='200' fill='url(%23g)'/><circle cx='80' cy='90' r='30' fill='white' opacity='0.18'/><circle cx='130' cy='130' r='22' fill='white' opacity='0.12'/></svg>`
  )}")`;

const CATEGORIES = [
  { id: "all", name: "전체", count: 24 },
  { id: "bouquet", name: "꽃다발", count: 8 },
  { id: "basket", name: "꽃바구니", count: 6 },
  { id: "wreath", name: "축하화환", count: 4 },
  { id: "vase", name: "화병꽂이", count: 3 },
  { id: "potted", name: "화분", count: 3 },
];

const PRODUCTS = [
  {
    id: "p_001",
    name: "봄의 인사 — 라넌큘러스 꽃다발",
    category: "bouquet",
    categoryName: "꽃다발",
    price: 58000,
    sizes: ["S", "M", "L"],
    tags: ["봄", "베스트", "선물"],
    status: "live",
    draft: false,
    visible: true,
    image: flowerThumb("#f4c8d0", "#d36a8a"),
    updatedAt: "5월 20일 14:22",
    stock: "주문제작",
    description: "라넌큘러스 12송이와 유칼립투스를 메인으로 한 시즌 한정 꽃다발",
  },
  {
    id: "p_002",
    name: "달콤한 봄 — 핑크 작약 꽃다발",
    category: "bouquet",
    categoryName: "꽃다발",
    price: 72000,
    sizes: ["M", "L"],
    tags: ["봄", "프로포즈"],
    status: "live",
    draft: true,
    visible: true,
    image: flowerThumb("#fbd5e2", "#e87fa3"),
    updatedAt: "5월 21일 09:15",
    stock: "주문제작",
    description: "탐스러운 핑크 작약 8송이와 베이비 안개꽃의 조합",
  },
  {
    id: "p_003",
    name: "감사의 마음 — 카네이션 꽃바구니",
    category: "basket",
    categoryName: "꽃바구니",
    price: 45000,
    sizes: ["S", "M"],
    tags: ["어버이날", "감사"],
    status: "draft",
    draft: true,
    visible: false,
    image: flowerThumb("#fde2c8", "#e8a268"),
    updatedAt: "5월 21일 11:03",
    stock: "주문제작",
    description: "카네이션과 시즌 그린을 담은 미니 꽃바구니",
  },
  {
    id: "p_004",
    name: "축하 스탠드 화환 3단",
    category: "wreath",
    categoryName: "축하화환",
    price: 120000,
    sizes: ["L"],
    tags: ["축하", "개업"],
    status: "live",
    draft: false,
    visible: true,
    image: flowerThumb("#ffefc1", "#e8c45f"),
    updatedAt: "5월 18일 16:40",
    stock: "주문제작",
    description: "개업·결혼식·전시회용 스탠드 화환. 메시지 카드 무료 동봉",
  },
  {
    id: "p_005",
    name: "유러피안 가든 — 들꽃 부케",
    category: "bouquet",
    categoryName: "꽃다발",
    price: 48000,
    sizes: ["S", "M"],
    tags: ["내추럴", "베스트"],
    status: "live",
    draft: false,
    visible: true,
    image: flowerThumb("#dde6c5", "#8fb178"),
    updatedAt: "5월 17일 10:22",
    stock: "주문제작",
    description: "라벤더·캐모마일·왁스플라워가 어우러진 자연스러운 부케",
  },
  {
    id: "p_006",
    name: "튤립 꽃다발 — 무지개 믹스",
    category: "bouquet",
    categoryName: "꽃다발",
    price: 38000,
    sizes: ["S", "M", "L"],
    tags: ["봄", "튤립"],
    status: "live",
    draft: false,
    visible: false,
    image: flowerThumb("#ffd6c1", "#e87a52"),
    updatedAt: "5월 16일 14:00",
    stock: "품절",
    description: "5가지 컬러의 튤립을 풍성하게 묶은 시그니처 꽃다발",
  },
  {
    id: "p_007",
    name: "수국 화분 — 마린블루",
    category: "potted",
    categoryName: "화분",
    price: 35000,
    sizes: ["M"],
    tags: ["인테리어", "수국"],
    status: "live",
    draft: false,
    visible: true,
    image: flowerThumb("#cfdcf4", "#7191c9"),
    updatedAt: "5월 15일 09:30",
    stock: "재고 3",
    description: "햇빛이 잘 드는 곳에 두기 좋은 마린블루 수국 화분",
  },
  {
    id: "p_008",
    name: "프리저브드 장미 액자",
    category: "vase",
    categoryName: "화병꽂이",
    price: 89000,
    sizes: ["M"],
    tags: ["프리저브드", "선물"],
    status: "live",
    draft: false,
    visible: true,
    image: flowerThumb("#f2d6d6", "#c47879"),
    updatedAt: "5월 14일 17:10",
    stock: "재고 2",
    description: "2년 이상 유지되는 프리저브드 장미 액자 — 메시지 각인 가능",
  },
];

// Home sections (H01)
const HOME_SECTIONS = [
  {
    id: "hero",
    type: "hero",
    icon: "image",
    title: "히어로",
    enabled: true,
    data: {
      headline: "오늘의 봄, 한 다발",
      subhead: "도화원플라워 — 도화동 골목 끝 작은 꽃집에서, 오늘 가장 좋은 꽃을 골라 드려요.",
      ctaPrimary: "오늘의 꽃 보기",
      ctaSecondary: "주문 문의",
      image: flowerThumb("#f8d7d8", "#e587a1"),
    },
  },
  {
    id: "greeting",
    type: "greeting",
    icon: "user",
    title: "인사말",
    enabled: true,
    data: {
      title: "도화원플라워에 오신 것을 환영합니다",
      body:
        "8년째 도화동에서 꽃집을 운영하며, 그 날의 가장 좋은 꽃만을 정성껏 골라 다발로 묶어 드리고 있어요. 모든 꽃은 주문 받으신 그 날 아침에 새벽 꽃시장에서 직접 사 온 것들입니다.",
    },
  },
  {
    id: "featured",
    type: "featured",
    icon: "star",
    title: "이번 주 추천",
    enabled: true,
    data: {
      title: "이번 주, 박소연이 고른 꽃",
      pickedIds: ["p_001", "p_005", "p_008"],
    },
  },
  {
    id: "info",
    type: "info",
    icon: "info",
    title: "매장 정보",
    enabled: true,
    data: {
      address: "서울 마포구 도화동 12-3",
      hours: "평일 10:00 ~ 19:00 · 일요일 휴무",
      phone: "010-9000-3333",
      instagram: "@dohwawon_flower",
    },
  },
  {
    id: "notice",
    type: "notice",
    icon: "bell",
    title: "공지",
    enabled: false,
    data: {
      body: "5월 23일~25일은 어버이날 주문이 몰려 픽업만 가능합니다.",
    },
  },
];

// Recent publish history
const PUBLISH_HISTORY = [
  {
    id: "pub_012",
    when: "5월 19일 09:42",
    author: "박소연",
    note: "어버이날 카네이션 꽃바구니 가격 인상 (+3,000원)",
    items: { products: 6, categories: 0, home: 1 },
    status: "success",
    duration: "1분 47초",
  },
  {
    id: "pub_011",
    when: "5월 17일 21:08",
    author: "박소연",
    note: "튤립 꽃다발 신규 등록 + 메인 히어로 카피 수정",
    items: { products: 1, categories: 0, home: 2 },
    status: "success",
    duration: "2분 12초",
  },
  {
    id: "pub_010",
    when: "5월 15일 11:30",
    author: "박소연",
    note: "수국 화분 시즌 상품 추가",
    items: { products: 3, categories: 1, home: 0 },
    status: "success",
    duration: "1분 38초",
  },
  {
    id: "pub_009",
    when: "5월 12일 18:21",
    author: "박소연",
    note: "어머니날 배너 임시 게재",
    items: { products: 0, categories: 0, home: 1 },
    status: "failed",
    error: "배포 권한 만료 — 슈퍼 어드민에게 갱신 요청 후 재시도",
    duration: "—",
  },
  {
    id: "pub_008",
    when: "5월 10일 09:14",
    author: "박소연",
    note: "신규 시즌 카테고리 '봄' 추가",
    items: { products: 4, categories: 1, home: 0 },
    status: "success",
    duration: "2분 03초",
  },
];

Object.assign(window, {
  SITES,
  CATEGORIES,
  PRODUCTS,
  HOME_SECTIONS,
  PUBLISH_HISTORY,
  flowerThumb,
});
